FROM golang:1.25-alpine AS builder

WORKDIR /app

COPY go.mod go.sum ./

RUN go mod download

COPY . .

RUN CGO_ENABLED=0 GOOS=linux go build -o app ./api-gateway/cmd

FROM alpine:3.22

WORKDIR /app

COPY --from=builder /app/app .
EXPOSE 3000

CMD ["./app"]